remote_theme: QuaereMe/Balzac-for-Jekyll
title: Quaere Me
description: A Blog by Christopher Bartz
canonical: https://quaere.me

# Owner/author information
owner:
  twitter:        QuaereMe
  github:         QuaereMe

links:
  - title: Store
    url: https://store.quaere.me
    external: true
